# Generated by Django 4.2.6 on 2023-12-14 02:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_post_caption_post_description_delete_demand'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='who_liked',
            field=models.ManyToManyField(blank=True, related_name='who_liked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
