# Generated by Django 4.2.6 on 2023-12-14 04:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='amount_of_followers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='amount_of_following',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='followers',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
