# Generated by Django 4.2.6 on 2023-12-16 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_post_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='posts',
            field=models.ManyToManyField(blank=True, related_name='user_posts', to='myapp.post'),
        ),
    ]
