# Generated by Django 4.2.6 on 2023-12-22 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_user_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='posts',
        ),
    ]
