# Generated by Django 4.2.6 on 2023-12-28 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_comment_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='comment',
            field=models.IntegerField(default=0),
        ),
    ]
